/// The JSON-schema-relevant class of a scalar leaf, classified by the
/// derive from the Rust type name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum ScalarHint {
    /// Anything parsed from a string (`String`, `PathBuf`, `Duration`,
    /// custom `FromStr` types).
    String,
    /// `i8` to `i128`, `u8` to `u128`, `isize`, `usize`.
    Integer,
    /// `f32`, `f64`.
    Float,
    /// `bool`.
    Bool,
}

/// Describes a field's structural shape for runtime CLI construction and
/// the `required` check.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub enum FieldType {
    /// A boolean field (special-cased for CLI flags that take no value).
    Bool,
    /// Any scalar type that implements `FromStr` (including `Option`s of one).
    Scalar,
    /// A `Vec<T>` of scalars.
    List,
    /// A map with scalar values.
    Map,
    /// A nested struct that derives `Config` (including `Option`s of one).
    Struct(Vec<FieldInfo>),
    /// A `Vec` of nested structs.
    StructList(Vec<FieldInfo>),
    /// A map of nested structs.
    StructMap(Vec<FieldInfo>),
}

/// Metadata about a single config struct field, generated by the derive
/// macro. Consumed by the runtime to build the clap command, resolve
/// origin details, and check `required` fields.
#[derive(Debug, Clone, PartialEq)]
pub struct FieldInfo {
    /// The Rust field name (e.g. `max_connections`).
    pub field_name: &'static str,
    /// The config key name from the `name` attribute (e.g. `max-connections`).
    pub config_name: &'static str,
    /// This field's env var segment: the config name uppercased with `-`
    /// folded to `_`, or the verbatim `env = "..."` override.
    pub env_segment: &'static str,
    /// This field's flag name segment: the config name, or the verbatim
    /// `flag = "..."` override.
    pub flag_segment: &'static str,
    /// `env = "-"`: this field is not settable from the environment.
    pub skip_env: bool,
    /// `flag = "-"`: this field is not settable from the CLI.
    pub skip_cli: bool,
    /// `short = 'p'`: single-character flag shorthand.
    pub short: Option<char>,
    /// `secret`: redacted in `print_config()` and parse errors.
    pub secret: bool,
    /// `required`: some layer must set this field.
    pub required: bool,
    /// Default value as a string, if specified.
    pub default_value: Option<&'static str>,
    /// Description for CLI help text.
    pub description: Option<&'static str>,
    /// For scalar leaves (and elements of scalar lists/maps): the
    /// schema-relevant class of the type.
    pub scalar: ScalarHint,
    /// The field is an `Option`.
    pub optional: bool,
    /// For nested struct fields (and struct collections): the struct has
    /// `#[configulator(allow_unknown_fields)]`.
    pub allow_unknown_fields: bool,
    /// The field's structural type.
    pub field_type: FieldType,
}
